# Generated by Django 4.1.7 on 2023-03-26 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='fabricante',
            options={'verbose_name_plural': 'Fabricantes'},
        ),
        migrations.AlterModelOptions(
            name='veiculo',
            options={'verbose_name_plural': 'Veículos'},
        ),
    ]
