# Generated by Django 4.1.7 on 2023-04-04 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_cliente_options_alter_fabricante_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabricante',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo_fabricante', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='placa',
            field=models.CharField(max_length=10, verbose_name='Placa'),
        ),
    ]
