# Generated by Django 4.1.7 on 2023-04-12 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_tabelapreco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='cliente_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='fabricante_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.fabricante', verbose_name='Fabricante'),
        ),
    ]
